### ISSUE TITLE
EADDRINUSE error

### ISSUE THREAD

**Issue by alexcarrega** [bezoerb/gulp-php2html#5]
Using gulp-php2html I get this error:

```javascript
	throw er; // Unhandled 'error' event
		  ^
	Error: listen EADDRINUSE
		at exports._errnoException (util.js:746:11)
		at Server._listen2 (net.js:1129:14)
		at listen (net.js:1155:10)
		at Server.listen (net.js:1240:5)
		at C:\Users\Alex\AppData\Roaming\npm\node_modules\gulp-php2html\node_modules\php2html\index.js:27:39)
		at fetchPort (C:\Users\Alex\AppData\Roaming\npm\node_modules\gulp-php2html\node_modules\php2html\index.js:54:4)
		at module.exports (C:\Users\Alex\AppData\Roaming\npm\node_modules\gulp-php2html\node_modules\php2html\index.js:125:2)
		at C:\Users\Alex\AppData\Roaming\npm\node_modules\gulp-php2html\index.js:80:4
		at C:\Users\Alex\AppData\Roaming\npm\node_modules\gulp-php2html\node_modules\async\lib\async.js:125:13
		at Array.forEach (native)
```

I tried with different value of port but I get the same error.

The Operating System is Windows 8.1

**Comment by cortopy** [comment]
Same here (although I'm using Ubuntu)

This is actually the problem I mentioned in https://github.com/giakki/uncss/issues/154#issuecomment-91509661

**Comment by bezoerb** [comment]
@cortopy could you try again using `master`? The port issue should be fixed there.

**Comment by alexcarrega** [comment]
@bezoerb Thanks, with `master` no problem.

**Comment by bezoerb** [comment]
https://github.com/bezoerb/gulp-php2html/releases/tag/v0.1.1

**Comment by cortopy** [comment]
I'm afraid new release doesn't solve the problem entirely for me. EADDRINUSE error message is gone.

But now I get:
```
Error: 404 - undefined
    at Server.<anonymous> (mypathtophp2html/index.js:160:10)
    at Server.g (events.js:180:16)
    at Server.EventEmitter.emit (events.js:92:17)
    at net.js:1273:10
    at process._tickCallback (node.js:415:13)
```

**Comment by bezoerb** [comment]
issue moved to #6
